/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vbtech.exe;

import java.text.DecimalFormat;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form ChartAdminPanel
     */
    private Connection con;

    public AdminPanel() {
        initComponents();
        connect();
        LoadTable();

    }

    private void connect() {
        try {
            String url = "jdbc:mysql://localhost:3307/account";
            String user = "root";
            String password = "112302";

            con = DriverManager.getConnection(url, user, password);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void AddTable(String prodcode, String product, double price, int qty, double totalprice) {
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        // Remove if prodcode already exists
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            if (prodcode.equals(jTable1.getValueAt(row, 0).toString())) {
                dt.removeRow(jTable1.convertRowIndexToModel(row));
                break;
            }
        }

        // Add new row
        Vector v = new Vector();
        v.add(prodcode);
        v.add(product);
        v.add(price);
        v.add(qty);
        v.add(totalprice);
        dt.addRow(v);
    }

    public void LoadTable() {
        try {
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            dt.setRowCount(0);  // Clear existing rows

            String query = "SELECT id, prodcode, product, price, qty, totalprice FROM inventory";
            java.sql.Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Add rows from database
            while (rs.next()) {
                int dbId = rs.getInt("id");  // Store database ID (hidden)
                String prodcode = rs.getString("prodcode");
                String product = rs.getString("product");
                double price = rs.getDouble("price");
                int qty = rs.getInt("qty");
                double totalprice = rs.getDouble("totalprice");

                Vector v = new Vector();
                v.add(prodcode);  // Display prodcode as first column
                v.add(product);
                v.add(price);
                v.add(qty);
                v.add(totalprice);
                v.add(dbId);  // Store database ID in hidden column (column 5)
                dt.addRow(v);
            }

            rs.close();
            stmt.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading table: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Accountbtn = new javax.swing.JButton();
        ReportBtn = new javax.swing.JButton();
        Monitoring = new javax.swing.JButton();
        StockBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inv_qty = new javax.swing.JTextField();
        inv_price = new javax.swing.JTextField();
        inv_id = new javax.swing.JTextField();
        inv_product = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DASHBOARD");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1280, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 180, 70));

        Accountbtn.setBackground(new java.awt.Color(102, 153, 255));
        Accountbtn.setText("ACCOUNT");
        Accountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Accountbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 70));

        ReportBtn.setBackground(new java.awt.Color(102, 153, 255));
        ReportBtn.setText("REPORT");
        ReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 70));

        Monitoring.setBackground(new java.awt.Color(255, 51, 51));
        Monitoring.setText("MONITORING");
        Monitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitoringActionPerformed(evt);
            }
        });
        jPanel1.add(Monitoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        StockBtn.setBackground(new java.awt.Color(102, 153, 255));
        StockBtn.setText("STOCK");
        jPanel1.add(StockBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 510));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addTab("DAILY SALES", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("QTY");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, -1));

        jLabel3.setText("ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 30, -1));

        jLabel4.setText("ID");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 30, -1));

        jLabel5.setText("PRODUCT");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        jLabel6.setText("PRICE");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, -1));
        jPanel4.add(inv_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, -1));
        jPanel4.add(inv_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 90, -1));
        jPanel4.add(inv_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, -1));

        inv_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_productActionPerformed(evt);
            }
        });
        jPanel4.add(inv_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCT", "PRICE", "QTY", "TOTALVALIE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 450, 250));

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel4.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 20));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel4.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        delbtn.setText("DELETE");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });
        jPanel4.add(delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jTabbedPane1.addTab("INVENTORY", jPanel4);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 510));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 1100, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonitoringActionPerformed
        AdminPanel ap = new AdminPanel();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_MonitoringActionPerformed

    private void AccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountbtnActionPerformed
        Register r = new Register();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_AccountbtnActionPerformed

    private void ReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginPanel lp = new LoginPanel();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        try {
            // Get values from text fields
            String prodcode = inv_id.getText().trim();
            String product = inv_product.getText().trim();
            String priceText = inv_price.getText().trim();
            String qtyText = inv_qty.getText().trim();

            // Validation
            if (prodcode.isEmpty() || product.isEmpty() || priceText.isEmpty() || qtyText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Convert to proper types
            double price = Double.parseDouble(priceText);
            int qty = Integer.parseInt(qtyText);
            double totalprice = price * qty;

            // Save to database (prodcode must be unique)
            String query = "INSERT INTO inventory (prodcode, product, price, qty, totalprice) VALUES (?, ?, ?, ?, ?) "
                    + "ON DUPLICATE KEY UPDATE product=?, price=?, qty=?, totalprice=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, prodcode);
            pst.setString(2, product);
            pst.setDouble(3, price);
            pst.setInt(4, qty);
            pst.setDouble(5, totalprice);
            pst.setString(6, product);
            pst.setDouble(7, price);
            pst.setInt(8, qty);
            pst.setDouble(9, totalprice);
            pst.executeUpdate();
            pst.close();

            // Clear fields
            inv_id.setText("");
            inv_product.setText("");
            inv_price.setText("");
            inv_qty.setText("");

            // Reload table
            LoadTable();

            JOptionPane.showMessageDialog(this, "Added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Price and Qty must be numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void inv_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inv_productActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed

         int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to update!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // Get the OLD prodcode from the selected row (to find the record)
        String oldProdcode = jTable1.getValueAt(selectedRow, 0).toString().trim();
        
        // Get NEW values from text fields
        String newProdcode = inv_id.getText().trim();
        String product = inv_product.getText().trim();
        String priceText = inv_price.getText().trim();
        String qtyText = inv_qty.getText().trim();
        
        // Validation
        if (oldProdcode == null || oldProdcode.isEmpty() || oldProdcode.equals("NULL")) {
            JOptionPane.showMessageDialog(this, "Invalid product code!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (newProdcode.isEmpty() || product.isEmpty() || priceText.isEmpty() || qtyText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Convert to proper types
        double price = Double.parseDouble(priceText);
        int qty = Integer.parseInt(qtyText);
        double totalprice = price * qty;
        
        System.out.println("Old Prodcode: " + oldProdcode);
        System.out.println("New Prodcode: " + newProdcode);
        System.out.println("Product: " + product + " | Price: " + price + " | Qty: " + qty + " | Totalprice: " + totalprice);
        
        // Update database - UPDATE ALL FIELDS including prodcode
        String query = "UPDATE inventory SET prodcode=?, product=?, price=?, qty=?, totalprice=? WHERE prodcode=?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, newProdcode);   // New prodcode
        pst.setString(2, product);       // New product
        pst.setDouble(3, price);         // New price
        pst.setInt(4, qty);              // New qty
        pst.setDouble(5, totalprice);    // New totalprice
        pst.setString(6, oldProdcode);   // WHERE clause (find by old prodcode)
        
        int result = pst.executeUpdate();
        pst.close();
        
        System.out.println("Update result: " + result + " rows affected");
        
        if (result > 0) {
            // Update table UI with ALL new values
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            dt.setValueAt(newProdcode, selectedRow, 0);   // Update prodcode
            dt.setValueAt(product, selectedRow, 1);       // Update product
            dt.setValueAt(price, selectedRow, 2);         // Update price
            dt.setValueAt(qty, selectedRow, 3);           // Update qty
            dt.setValueAt(totalprice, selectedRow, 4);    // Update totalprice
            
            // Clear fields
            inv_id.setText("");
            inv_product.setText("");
            inv_price.setText("");
            inv_qty.setText("");
            
            JOptionPane.showMessageDialog(this, "Updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Reload table to refresh from database
            LoadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Record not found! Prodcode: " + oldProdcode, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Price and Qty must be numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

    }//GEN-LAST:event_updatebtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed

 
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to delete!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        String prodcode = jTable1.getValueAt(selectedRow, 0).toString();
        
        if (prodcode == null || prodcode.isEmpty() || prodcode.equals("NULL")) {
            JOptionPane.showMessageDialog(this, "Invalid product code! Cannot delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            // Delete from database using prodcode
            String query = "DELETE FROM inventory WHERE prodcode = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, prodcode);
            int result = pst.executeUpdate();
            pst.close();
            
            if (result > 0) {
                // Delete from table
                DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
                
                // Check if row is still valid
                if (selectedRow < dt.getRowCount()) {
                    dt.removeRow(selectedRow);
                }
                
                JOptionPane.showMessageDialog(this, "Deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                // Reload table to refresh
                LoadTable();
            } else {
                JOptionPane.showMessageDialog(this, "Record not found in database!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
 inv_id.setText("");
            inv_product.setText("");
            inv_price.setText("");
            inv_qty.setText("");

    }//GEN-LAST:event_delbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();

        inv_id.setText(jTable1.getValueAt(selectedRow, 0).toString());        // prodcode
        inv_product.setText(jTable1.getValueAt(selectedRow, 1).toString());   // product
        inv_price.setText(jTable1.getValueAt(selectedRow, 2).toString());     // price
        inv_qty.setText(jTable1.getValueAt(selectedRow, 3).toString());       // qty        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accountbtn;
    private javax.swing.JButton Monitoring;
    private javax.swing.JButton ReportBtn;
    private javax.swing.JButton StockBtn;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton delbtn;
    private javax.swing.JTextField inv_id;
    private javax.swing.JTextField inv_price;
    private javax.swing.JTextField inv_product;
    private javax.swing.JTextField inv_qty;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
