/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vbtech.exe;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author user
 */


public class Register extends javax.swing.JFrame {

    /**
     * Creates new form ChartAdminPanel
     */
    private Connection con;
    public Register() {
        initComponents();
     connect();
         
    }
    
 

     
        private void connect() {
        try {
            String url = "jdbc:mysql://localhost:3307/account";
            String user = "root";
            String password = "112302";

            con = DriverManager.getConnection(url, user, password);

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    
    
    public void AddTable(String FIRSTNAME,String LASTNAME , String CONTACT, String EMAIL, String ROLE) {
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            if (FIRSTNAME == jTable1.getValueAt(row, 1)) {
                dt.removeRow(jTable1.convertRowIndexToModel(row));
            }

        }

        Vector v = new Vector();

        v.add(FIRSTNAME);
        v.add(LASTNAME);
        v.add(CONTACT);
        v.add(EMAIL);
        v.add(ROLE);
        
        dt.addRow(v);

    }
    
    
    public void loadTable() {
    try {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        String sql = "SELECT firstname, lastname, contact, email, role FROM users";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("firstname"),
                rs.getString("lastname"),
                rs.getInt("contact"),
                rs.getString("email"),
                rs.getString("role")
            });
        }

        rs.close();
        pst.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        MonitoringBtn = new javax.swing.JButton();
        ReportBtn = new javax.swing.JButton();
        AccountBtn = new javax.swing.JButton();
        StockBtn = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cFirstName = new javax.swing.JTextField();
        cLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cUserName = new javax.swing.JTextField();
        cPassword = new javax.swing.JPasswordField();
        cRole = new javax.swing.JComboBox<>();
        Createbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CREATE ACCOUNT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1280, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 180, 70));

        MonitoringBtn.setBackground(new java.awt.Color(102, 153, 255));
        MonitoringBtn.setText("MONITORING");
        MonitoringBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitoringBtnActionPerformed(evt);
            }
        });
        jPanel1.add(MonitoringBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 70));

        ReportBtn.setBackground(new java.awt.Color(102, 153, 255));
        ReportBtn.setText("REPORT");
        ReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 70));

        AccountBtn.setBackground(new java.awt.Color(255, 51, 51));
        AccountBtn.setText("Create Staff ACCOUNT");
        AccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        StockBtn.setBackground(new java.awt.Color(102, 153, 255));
        StockBtn.setText("STOCK");
        jPanel1.add(StockBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 510));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRSTNAME");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));
        jPanel4.add(cFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, -1));
        jPanel4.add(cLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LASTNAME");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 70, 20));

        cContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cContactActionPerformed(evt);
            }
        });
        jPanel4.add(cContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTACT");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 30));

        cUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUserNameActionPerformed(evt);
            }
        });
        jPanel4.add(cUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 120, -1));

        cPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPasswordActionPerformed(evt);
            }
        });
        jPanel4.add(cPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 120, -1));

        cRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        jPanel4.add(cRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        Createbtn.setText("CREATE");
        Createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatebtnActionPerformed(evt);
            }
        });
        jPanel4.add(Createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PASSWORD");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ROLE");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USERNAME");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, 30));

        cEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEmailActionPerformed(evt);
            }
        });
        jPanel4.add(cEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 120, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 150));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIRSTNAME", "LASTNAME", "CONTACT", "EMAIL", "ROLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1100, 360));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 1100, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBtnActionPerformed
      
    }//GEN-LAST:event_AccountBtnActionPerformed

    private void MonitoringBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonitoringBtnActionPerformed
        AdminPanel Ap = new AdminPanel();
        Ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_MonitoringBtnActionPerformed

    private void ReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      LoginPanel lp = new LoginPanel();
      lp.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatebtnActionPerformed
       
        try {

        String firstname = cFirstName.getText().trim();
        String lastname = cLastName.getText().trim();
        String username = cUserName.getText().trim();
        String password = String.valueOf(cPassword.getPassword());
        String email = cEmail.getText().trim();
         String contact = cContact.getText().trim();
        String role = cRole.getSelectedItem().toString();

        if (firstname.isEmpty() || lastname.isEmpty()
                || username.isEmpty() || password.isEmpty()
                || email.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Please fill all fields!");
            return;
        }

        if (con == null) {
            JOptionPane.showMessageDialog(this,
                    "Database connection failed!");
            return;
            
         
            
        }  
        

        String sql = "INSERT INTO users "
                + "(firstname, lastname, username, password, role, email, contact) "
                + "VALUES (?, ?, ?, ?, ?, ?,?)";

        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, firstname);
        pst.setString(2, lastname);
        pst.setString(3, username);
        pst.setString(4, password);
        pst.setString(5, role);
       
        pst.setString(6, email);
        pst.setString(7, contact);
        
        int result = pst.executeUpdate();
         loadTable();

        if (result > 0) {

            JOptionPane.showMessageDialog(this,
                    "Account Created Successfully!");

            cFirstName.setText("");
            cLastName.setText("");
            cUserName.setText("");
            cPassword.setText("");
            cEmail.setText("");
            cContact.setText("");
            cRole.setSelectedIndex(0);

            
        }

        pst.close();

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this,
                "Error: " + ex.getMessage());

    }
        
    }//GEN-LAST:event_CreatebtnActionPerformed

    private void cPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPasswordActionPerformed

    private void cUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUserNameActionPerformed

    private void cEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmailActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    int row = jTable1.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this account?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {

        String firstname = jTable1.getValueAt(row, 0).toString();
        String lastname = jTable1.getValueAt(row, 1).toString();
        String email = jTable1.getValueAt(row, 3).toString();

        String sql = "DELETE FROM users WHERE firstname=? AND lastname=? AND email=?";

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, firstname);
        pst.setString(2, lastname);
        pst.setString(3, email);

        int result = pst.executeUpdate();

        if (result > 0) {

            JOptionPane.showMessageDialog(this, "Account deleted successfully.");

            loadTable();

            cFirstName.setText("");
            cLastName.setText("");
            cContact.setText("");
            cEmail.setText("");
            cUserName.setText("");
            cPassword.setText("");
            cRole.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(this, "Account not found.");
        }

        pst.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountBtn;
    private javax.swing.JButton Createbtn;
    private javax.swing.JButton MonitoringBtn;
    private javax.swing.JButton ReportBtn;
    private javax.swing.JButton StockBtn;
    private javax.swing.JTextField cContact;
    private javax.swing.JTextField cEmail;
    private javax.swing.JTextField cFirstName;
    private javax.swing.JTextField cLastName;
    private javax.swing.JPasswordField cPassword;
    private javax.swing.JComboBox<String> cRole;
    private javax.swing.JTextField cUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
